# fly.toml app configuration file generated for pixel-project on 2025-08-20T20:08:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixel-project"
primary_region = "atl"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DB_FILE = "/data/data.sqlite"
  CORS_ORIGIN = "https://pixel-project.fly.dev"
  FRONTEND_ORIGIN = "https://pixel-project.fly.dev"
  CENTS_PER_CELL = "2500"
  MIN_AMOUNT_CENTS = "100"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  # Cost/latency trade-off:
  # If you want lowest cost, keep these 2 lines:
  auto_stop_machines = "stop"
  min_machines_running = 0
  # If you want instant wake + socket readiness, change to:
  # auto_stop_machines = false
  # min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

